#!/bin/bash

echo "Eingabedatei?"
read infile
echo "Ausgabedatei?"
read outfile
while read line; do
    echo \n$line
    echo "Wie viele Karten?"
    read number < /dev/tty
    printf "{\n  \"content\": \"$line\",\n  \"pick\": $number,\n  \"draw\": $number\n},\n" >> $outfile
done <$infile
